### PR TITLE
Update model icub and walkman

### PR DESCRIPTION
**Pull request by gabrielenava**
updated iCubGenova02 and icubGazeboSIm models by adding contact frames on the legs. Updated walkman urdf.

### CODE REVIEW

**Comment by traversaro** [comment]
If we plan to perform the stand up demonstration on the iCubNancy01, we need to bring the `l_upper_leg_contact` frame at least in the iCubNancy01 model.

**Comment by gabrielenava** [comment]
If iCubNancy01 is a v.2.5 iCub with backpack like the purple and the green, this can be done (for now) by copying the iCubGenova02 model in iCubNancy01 folder. Otherwise we have to wait for the (already in progress) addition of the required frames in the CAD model

**Comment by traversaro** [comment]
As discussed f2f : iCubNancy is a v2.5 with arm v1 (probably, according to the photos in https://github.com/robotology-playground/icub-model-generator/issues/13#issuecomment-241366485). For the purpose of replicating the iCub stand up demo the best strategy is perhaps to use a model v2.5 without backpack . Such a model will have the wrong kinematics for the forearm, but the effect of this on the standup demo will be probably negligible. 
We will need anyhow to properly document (and remember) that whenever we will be use the kinematics information of the forearm.

**Comment by francesco-romano** [comment]
Nancy will be added later.

**Pull request merged**
